### ISSUE TITLE
PEER DEPENDENCY ERROR!

### ISSUE THREAD

**Issue by iamshour** [Detaysoft/react-chat-elements#171]
Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-chat-elements@12.0.0
npm ERR! node_modules/react-chat-elements
npm ERR!   react-chat-elements@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by GeorgeFlorian** [comment]
I also have this.

Will this package get a bumped React version ?

**Comment by Smyja** [comment]
> I also have this.
> 
> Will this package get a bumped React version ?

also wondering when it will be resolved

**Comment by scailbc** [comment]
I think this was solved in v12.0.8, where React was upgraded to v18.

Anyway, my preferred solution is the [overrides option of the package.json](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides), that does not require the `--force` flag

```js
  "dependencies": {
    "react": "18.2.0",
    "react-chat-elements": "12.0.0",
    "react-dom": "18.2.0",
  },
  "overrides": {
    "react-chat-elements": {
      "react": "$react",
      "react-dom": "$react-dom"
    }
  },
```

**Comment by jiexiangfan** [comment]
```
npm ERR! Found: react-dom@18.3.1
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^18.3.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-dom@"18.2.0" from react-chat-elements@12.0.15
npm ERR! node_modules/react-chat-elements
npm ERR!   react-chat-elements@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
FYI the error is still happening, although it could be done by adding `--legacy-peer-deps`

**Comment by abdurrahmanekr** [comment]
If you want to fix this issue you can open a PR to this repo. In this way you will also make a contribution to the people who use this project.
