### ISSUE TITLE
Not able to render custom component in message box

### ISSUE THREAD

**Issue by zaahmed-nisum-com** [Detaysoft/react-chat-elements#185]
<MessageBox
        styles={{ border: 'solid' }}
        classNam="message"
        type={'text'}
        renderAddCmp={() => {
          return (<div className='message-c'></div>)
        }}
      />
and/or

<MessageBox
        styles={{ border: 'solid' }}
        classNam="message"
        type={'te'}
        renderAddCmp={<CustomMessage />}
      />

**Comment by emregudur** [comment]
Fixed in 12.0.8

**Comment by JJack27** [comment]
This issue still exist. The text out of the message box is the returned content from renderAddCmp.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/7407727/231957802-19ca9fb6-337c-4345-86da-ae79362c1143.png">
